apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-cert
  namespace: homepage
spec:
  secretName: homepage-tls-secret
  issuerRef:
    name: ss-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - homepage.homelab.sb
