apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drawio-cert
  namespace: homelab-drawio
spec:
  secretName: drawio-tls-secret
  issuerRef:
    name: ss-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - drawio.homelab.sb
