apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: homelab-drawio
  name: drawio-ingress
  annotations:
    #cert-manager.io/issuer: ss-ca-issuer
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
  labels:
    name: drawio-ingress
spec:
  rules:
    - host: homelab.drawio.sb
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: drawio-service
                port:
                  number: 5001
  tls:
    - hosts:
        - homelab.drawio.sb
      secretName: drawio-tls-secret
