name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  datree-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run tests on my Kubernetes YAML files
        run: |
          #!/bin/bash

          shopt -s globstar

          wget https://github.com/datreeio/datree/releases/download/1.9.22-rc/datree-cli_1.9.22-rc_Linux_x86_64.zip --quiet

          unzip datree-cli_1.9.22-rc_Linux_x86_64.zip -x README.md LICENSE.md

          chmod +x datree

          ./datree config set offline local

          ./datree test **/*.yml --only-k8s-files --ignore-missing-schemas --policy-config="datree-policies.yaml"
